apiVersion: gateway.kyma.cx/v1alpha2
kind: Api
metadata:
  name: javamaddressbook
  labels:
     app: javamaddressbook
spec:
  hostname: javamaddressbook
  service:
    name: javamaddressbook
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:    
     app: javamaddressbook
     version: "0.0.3"
  annotations:
     auth.istio.io/80: NONE
  name: javamaddressbook
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: javamaddressbook
    version: "0.0.3"
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
   annotations:
      deployment.kubernetes.io/revision: "3"
   labels:
      app: javamaddressbook
      mf_version: "1"
   name: javamaddressbook   
spec:
   replicas: 1
   selector:
      matchLabels:
         app: javamaddressbook
   template:
      metadata:
         labels:    
            app: javamaddressbook
            version: "0.0.3"
         annotations:
            sidecar.istio.io/inject: "true"
      spec:    
         containers:
           - name: javamaddressbook
# changeme: Replace with pointer to your docker repository/container
             image: provideImageName
             imagePullPolicy: Always              
             ports:
              - containerPort: 8080
                name: http

             env:
              - name: destinations
                valueFrom: 
                   configMapKeyRef:
                      name: javamaddressbookconfigmap
                      key: url 