
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: addressbook
  name: addressbook
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: addressbook
  template: 
    metadata: 
      labels: 
        app: addressbook
    spec: 
      containers: 
        - 
          image: "docker.io/dockerkyma/addressbook_latest:v1"
          name: addressbook
          ports: 
            - 
              containerPort: 8080
