--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ template "addressbook.fullname" . }}-java
  namespace: {{ $.Values.environment }}
spec: 
  replicas: {{ $.Values.replicaCount }}
  template: 
    metadata:
      name: addressbook
      labels: 
        chart: {{ template "addressbook.fullname" .}}
    spec: 
      containers: 
        - 
          image: ektajha/addressbooklatest:{{ $.Values.imagetag }}
          name: addressbook
          ports: 
            - 
              containerPort: 8080