--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ template "addressbook.fullname" . }}-java
  namespace: {{ $.Values.environment }}
spec: 
  replicas: {{ $.Values.replicaCount }}
  template: 
    metadata:
      name: {{ template "addressbook.fullname" .}}
      labels: 
        chart: {{ template "addressbook.fullname" .}}
    spec: 
      containers: 
        - 
          image: ektajha/addressbooklatest:{{ $.Values.imageversion }}
          name: addressbook
          ports: 
            - 
              containerPort: 8080