--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: addressbook
  name: addressbook
spec: 
  replicas: {{ $.Values.replicaCount }}
   selector: 
    matchLabels: 
      app: addressbook
  template: 
     metadata: 
      labels: 
        app: addressbook
    spec: 
      containers: 
        - 
          image: ektajha/addressbooklatest:{{ $.Values.imageversion }}
          name: addressbook
          ports: 
            - 
              containerPort: 8080