--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: addressbookjava
  name: addressbookjava
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: addressbookjava
  template: 
    metadata: 
      labels: 
        app: addressbookjava
    spec: 
      containers: 
        - 
          image: "docker.io/ektajha/addressbook"
          name: addressbookjava
          ports: 
            - 
              containerPort: 8080
          env:
          - name: destinations
              valueFrom: 
                 configMapKeyRef:
                    name: javaaddressbookconfigmap
                    key: url
