apiVersion: gateway.kyma.cx/v1alpha2
kind: Api
metadata:
  name: addressbook
  labels:
     app: addressbook
spec:
  hostname: addressbook
  service:
    name: addressbook
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:    
     app: addressbook
     version: "0.0.3"
  annotations:
     auth.istio.io/80: NONE
  name: addressbook
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: addressbook
    version: "0.0.3"
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
   annotations:
      deployment.kubernetes.io/revision: "3"
   labels:
      app: addressbook
      mf_version: "1"
   name: addressbook   
spec:
   replicas: 1
   selector:
      matchLabels:
         app: addressbook
   template:
      metadata:
         labels:    
            app: addressbook
            version: "0.0.3"
         annotations:
            sidecar.istio.io/inject: "true"
      spec:    
         containers:
           - name: addressbook
# changeme: Replace with pointer to your docker repository/container
             image: docker.io/ektajha/addressbook:{{.Values.imageversion}}
             imagePullPolicy: Always              
             ports:
              - containerPort: 8080
                name: http

             env:
              - name: destinations
                valueFrom: 
                   configMapKeyRef:
                      name: javaaddressbookconfigmap
                      key: url 