---
apiVersion: v1
kind: Service
metadata:
  labels:    
     app: mockserver
  name: mockserver
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: mockserver
  type: NodePort

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mockserver
  name: mockserver
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mockserver
  template: 
    metadata: 
      labels: 
        app: mockserver
    spec: 
      containers: 
        - 
          image: "docker.io/ektajha/mockserver:v10"
          name: mockserver
          ports: 
            - 
              containerPort: 3000